### ISSUE TITLE
Issue with platform search and no result

### ISSUE THREAD

**Issue by fdege** [netgen/ezplatformsearch#10]
Hi,

first thanks for this really useful extension! 

We found a problem with the bundle but i am not sure if it a general problem:
- if you search for a term in the legacy backend where not hit is found a SQL error occurs and a fatal error 
- the reason is that an empty nodelist is passed to 

nodes = eZContentObjectTreeNode::fetch( $nodeIds ); 

This ends in a query "WHERE node_id IN (  )" 

Code in search/plugins/ezplatformsearch/ezplatformsearch.php: 
Line 312:
`//  $nodeIds is an empty array
       $nodes = eZContentObjectTreeNode::fetch( $nodeIds );
        if ( $nodes instanceof eZContentObjectTreeNode )
        {
            $nodes = array( $nodes );
        }
        else if ( !is_array( $nodes ) )
        {
            $nodes = array();
        }`

**Comment by emodric** [comment]
Hi @fdege !

Thanks for the report, I've fixed the issue. Can you test so I can tag a new release for you?

**Comment by fdege** [comment]
Hi,

it works! You can tag a new release! Thanks again

**Comment by emodric** [comment]
@fdege Done!
