### ISSUE TITLE
extensions relies on search_engine parameter

### ISSUE THREAD

**Issue by andrerom** [netgen/ezplatformsearch#9]
Relying on "search_engine" parameter is sub optimal for several reasons:
- upgrades from 5.4 and 2014.11 won't have it
- a customer project with more complex setup might not use it at all as it is not multi repo friendly if you use solr for one and legacy for another one for instance.

So would be more reliable to check that Search engine handler is, or _is not_ LegacySearchEngine instance depending on case.

**Comment by jjCavalleri** [comment]
+1

**Comment by emodric** [comment]
Good point!

> a customer project with more complex setup might not use it at all as it is not multi repo friendly if you use solr for one and legacy for another one for instance.

How do you decide which implementation to use then? Would `ezpublish.spi.search` service be of correct type depending on the context?

**Comment by andrerom** [comment]
The param is just sugar_(, and some people prefer to stay off sugar)_, the SA aware setting is this one:
https://doc.ez.no/display/EZP/Solr+Search+Engine+Bundle#SolrSearchEngineBundle-Step5:Configuringrepositorywiththespecificsearchengine

I think `ezpublish.spi.search` should be ok to check also, at least atm there is no plans to wrap it like persistence is. But you never know, someone might make a slow query wrapper to log stuff.

pov @pspanja ?

**Comment by emodric** [comment]
Any other suggestions then? Checking the instance of `ezpublish.spi.search` is good enough for me (for now).

**Comment by pspanja** [comment]
Well, if you want to be complete one other option is to find configured search engine alias through information stored in `repository` and `ezpublish.repositories` parameters and then dispatch on that. But maybe that would be an overkill here, if someone has a need for it we do accept PRs :)

So +1 for instance of `ezpublish.spi.search`.

**Comment by emodric** [comment]
@pspanja @andrerom +1

@andrerom Do you need a tag?

**Comment by andrerom** [comment]
+1

> @andrerom Do you need a tag?

yes, patch tag please :)

**Comment by emodric** [comment]
@andrerom Done.

**Comment by andrerom** [comment]
Thanks @emodric ! :)
